### ISSUE TITLE
!vatsim returns unparsed object 

### ISSUE THREAD

**Issue by JOKUE2002** [drph4nt0m/avbot#96]
# Expected Behavior

I am expecting information on an aircraft if sending the `!vatsim [callsign]` command

## Current Behavior

The bot responds with `@<your_name_here> , [object Object]`

## Failure Information (for bugs)

The returned object has not been parsed before sending it in a reply to the user

## Steps to Reproduce

1. Fly on vatsim
2. type `!vatsim <your callsign here>`
Same happens with ATC-Callsigns (e.g. `!vatsim EPWW`  (Warszawa Radar))

**Comment by drph4nt0m** [comment]
Hey @JOKUE2002, it is a known issue. VATSIM recently deprecated their old API. I have to migrate the bot to use the new API. Expect an update soon.

**Comment by drph4nt0m** [comment]
Fixed.
